#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Static build: assemble the deployed pages from src/ templates + shared partials/.

  python3 build.py            # rebuild index.html + ruska-lozova.html
  python3 build.py --check    # fail if the committed HTML is stale (CI/pre-commit)

Edit the SOURCES, never the generated root *.html:
  - partials/header.html · partials/menu.html · partials/footer.html   (shared chrome)
  - src/<page>.html                                                    (per-page content)
Then run build and commit. GitHub Pages serves the generated root files as-is.

Templating (deliberately tiny):
  <!--#include partials/name.html-->   inject a partial (may nest)
  {{VAR}}                              per-page variable from PAGES below
"""
import io, os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))

# page  ->  source template + per-page variables
PAGES = {
    "index.html": {
        "src": "src/index.html",
        "vars": {"HOME": "", "LOGO_HREF": "#", "HEADER_META": "Харків · 49.99° N, 36.23° E"},
    },
    "ruska-lozova.html": {
        "src": "src/ruska-lozova.html",
        "vars": {"HOME": "index.html", "LOGO_HREF": "index.html", "HEADER_META": "кейс · 2024"},
    },
}

BANNER = ("  <!-- GENERATED by build.py from src/ + partials/. "
          "Do not edit this file directly — edit the sources and run: python3 build.py -->\n")
INCLUDE = re.compile(r"<!--#include\s+(\S+?)\s*-->")

def rd(p): return io.open(os.path.join(ROOT, p), encoding="utf-8").read()

def resolve_includes(s, _depth=0):
    if _depth > 10:
        raise RuntimeError("include nesting too deep (cycle?)")
    return INCLUDE.sub(lambda m: resolve_includes(rd(m.group(1)), _depth + 1), s)

def render(cfg):
    s = resolve_includes(rd(cfg["src"]))
    for k, v in cfg["vars"].items():
        s = s.replace("{{%s}}" % k, v)
    s = s.replace("<head>", "<head>\n" + BANNER, 1)
    leftover = re.findall(r"\{\{[A-Z_]+\}\}|<!--#include", s)
    if leftover:
        raise SystemExit("%s: unresolved tokens %s" % (cfg["src"], sorted(set(leftover))))
    return s

def main():
    check = "--check" in sys.argv
    stale = []
    for out, cfg in PAGES.items():
        built = render(cfg)
        fp = os.path.join(ROOT, out)
        current = io.open(fp, encoding="utf-8").read() if os.path.exists(fp) else None
        if check:
            if current != built:
                stale.append(out)
        else:
            if current != built:
                io.open(fp, "w", encoding="utf-8").write(built)
                print("built", out)
            else:
                print("up-to-date", out)
    if check and stale:
        raise SystemExit("STALE (run python3 build.py): " + ", ".join(stale))
    if check:
        print("all pages up-to-date")

if __name__ == "__main__":
    main()
